<?php use Snowdog\Academy\Model\Book;

require_once(__DIR__ . '/../../common/header.phtml'); 
$action = '/admin/show/0';
?>

<section id="add" class="padded">
    <a href="/admin/new_book" class="btn btn-primary">Add new book</a>
    <a href="/admin/load_book" class="btn btn-primary">Load books from .CSV</a>
</section>

<section id="search" class="padded"> 
    <form class="form-horizontal" method="POST" action="<?= $action ?>">
        <div class="form-group">
            <label for="borrowed-days" class="col-sm-3 control-label">Books borrowed more then (days): </label>
            <div class="col-sm-2">
                <input type="number" id="borrowed-days" name="number_of_days" class="form-control" min="0" max="99" value="<?=0?>" required/>
            </div>
            <div class="col-sm-1">
                <button type="submit" class="btn btn-primary">Show</button>
            </div>
        </div>
    </form>
</section>

<section id="book-list" class="padded">
    <h3>Book</h3>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>ID</th>
                <th>Title</th>
                <th>Author</th>
                <th>ISBN</th>
                <th>Is for child</th>
                <th>Borrowed</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->getBooks() as $book): /** @var Book $book */?>
            <tr>
                <td><?= $book->getId()?></td>
                <td><?= $book->getTitle()?></td>
                <td><?= $book->getAuthor()?></td>
                <td><?= $book->getIsbn()?></td>
                <td><?= $book->isForChild() ? 'Yes' : 'No' ?></td>
                <td><?= $book->isBorrowed() ? 'Yes' : 'No' ?></td>
                <td><a href="/admin/edit_book/<?=$book->getId()?>">Edit</a></td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</section>


<?php require_once(__DIR__ . '/../../common/footer.phtml'); ?>

