<?php use Snowdog\Academy\Model\Book;

require_once(__DIR__ . '/../../common/header.phtml');
$number_of_days=$this->numberOfDays->getNumber();
$action = '/admin/show/'.$this->numberOfDays->getNumber();
?>

<section id="search" class="padded"> 
    <form class="form-horizontal" method="POST" action="<?= $action ?>">
        <div class="form-group">
            <label for="borrowed-days" class="col-sm-3 control-label">Books borrowed more then (days):</label>
            <div class="col-sm-2">
                <input type="number" id="borrowed-days" name="number_of_days" class="form-control" min="0" max="99" value="<?=$number_of_days?>" required/>
            </div>
            <div class="col-sm-1">
                <button type="submit" class="btn btn-primary">Show</button>
            </div>
        </div>
    </form>
</section>

<section id="book-list1" class="padded">
    <?php
    $day="day";
    if($number_of_days!=1)
    {
        $day="days";
    } 
    ?>
    <h3>Book list borrowed more then <?= $number_of_days ?> <?=$day?></h3>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>ID</th>
                <th>Title</th>
                <th>Author</th>
                <th>ISBN</th>
                <th>Borrowed</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->getBooksByDays($number_of_days) as $book): /** @var Book $book */?>
            <tr>
                <td><?= $book->getId()?></td>
                <td><?= $book->getTitle()?></td>
                <td><?= $book->getAuthor()?></td>
                <td><?= $book->getIsbn()?></td>
                <td><?= $book->isBorrowed() ? 'Yes' : 'No' ?></td>
                <td><a href="/admin/edit_book/<?=$book->getId()?>">Edit</a></td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</section>

<?php require_once(__DIR__ . '/../../common/footer.phtml'); ?>